# Generated by Django 5.0.6 on 2024-11-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ponto",
            old_name="nome",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="ponto",
            old_name="lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="ponto",
            old_name="lng",
            new_name="longitude",
        ),
        migrations.AlterField(
            model_name="ponto",
            name="descricao",
            field=models.CharField(max_length=255),
        ),
    ]
